### ISSUE TITLE
Docs: instantiating video heartbeat

### ISSUE THREAD

**Issue by RyanEdwardHall** [Adobe-Marketing-Cloud/video-heartbeat#2]
In Video heartbeat SDK Guide for Javascript version 1.3.1, page 5, the video heartbeat library is instantiated with the following line:

`var VideoHeartbeat = ADB.heartbeat.VideoHeartbeat;`

However, ADB.heartbeat does not exist. There is ADB.core and ADB.va
I'm using: video heartbeats - v1.2.0 - 2014-04-25, which seems to be current.

Thanks!

**Comment by himanshuphalak** [comment]
Cleaning up old issues. Most of these were fixed in later releases or with 2.x SDKs.
