### ISSUE TITLE
Mismatched anonymous define

### ISSUE THREAD

**Issue by coderfin** [Adobe-Marketing-Cloud/video-heartbeat#5]
As explained here: http://requirejs.org/docs/errors.html#mismatch, "If you manually code a script tag in HTML to load a script with an anonymous define() call, [`the Mismatched anonymous define() module`] error can occur."

In the `VideoHeartbeat.js` JavaScript sdk on `line 297` there is an `anonymous define()`.  This is causing an error when `require.js` is added to the page in the `<head>` tag and `VideoHeartbeat.js` or a file containing `VideoHeartbeat.js` like `AppMeasurement.js` is added to the `<body>` tag.

You can see a replication of this error in this jsbin: http://jsbin.com/vusatiqama/1/watch?html,console

**Comment by aertmann** [comment]
Thanks for opening an issue, can confirm this through Arkena video which includes Heartbeat

**Comment by himanshuphalak** [comment]
Cleaning up this old issue as it has been fixed with later releases.
