### ISSUE TITLE
CocoaPod

### ISSUE THREAD

**Issue by stevelaw** [Adobe-Marketing-Cloud/video-heartbeat#7]
I do not see a publically available `video-heartbeat` CocoaPod.

I do see the `AdobeMobileSDK` available.

It would be nice to have a CocoaPod of the heartbeat library as well.

**Comment by ladanazita** [comment]
@andreifecioru Any updates on this?

**Comment by ladanazita** [comment]
@shalehah Do you know if this will be added to Cocoapods?

**Comment by himanshuphalak** [comment]
@ladanazita We will be adding our 2.x library located [here](https://github.com/Adobe-Marketing-Cloud/video-heartbeat-v2) to CocoaPod with our next release.

**Comment by ladanazita** [comment]
Nice! Any ETA on that?

**Comment by himanshuphalak** [comment]
@ladanazita we are working on it currently and it should be available soon. We will post an update once AdobeVideoHeartbeatSDK pod is available.

**Comment by himanshuphalak** [comment]
@ladanazita AdobeVideoHeartbeatSDK pod is now available on CocoaPods [here](https://cocoapods.org/pods/AdobeVideoHeartbeatSDK). Please note that this pod only supports 2.x SDK releases.

**Comment by ladanazita** [comment]
Thank you @himanshuphalak ! This is great :)
