### ISSUE TITLE
Use of unresolved identifier ASSET_TYPE_LIVE and ASSET_TYPE_VOD

### ISSUE THREAD

**Issue by mejim707** [Adobe-Marketing-Cloud/video-heartbeat#9]
After upgrading to the latest 7.3 version of Xcode with swift 2.2, the errors " Use of unresolved identifier 'ASSET_TYPE_LIVE' " and " Use of unresolved identifier 'ASSET_TYPE_VOD' " will be experienced if using with of these string constants. In order to resolve the issue, constants need to be moved outside of the class interface of ADB_VHB_AssetType.h. The below updated code resolved the issue.

```
#import <Foundation/Foundation.h>

/**
 * String util to be used if the asset type is "vod"
 */
extern NSString *const ASSET_TYPE_VOD;

/**
 * String util to be used if the asset type is "live"
 */
extern NSString *const ASSET_TYPE_LIVE;

/**
 * String util to be used if the asset type is "linear"
 */
extern NSString *const ASSET_TYPE_LINEAR;

@interface ADB_VHB_AssetType : NSObject

@end
```

**Comment by himanshuphalak** [comment]
cleaning up this issue since it is fixed with later 2.x releases.
